language: c
compiler:
  - clang
  - gcc
  
before_script:
  - uname -a  

script: 
  - chmod 777 configure
  - chmod 777 sysinfogen.sh
  - ./configure --enable-debug && make sql -j3
  - make clean
  - ./configure --disable-renewal --enable-debug && make sql -j3
  
notifications:
  email: false
  
branches:
  only:
    - master
